### PR TITLE
fix: some issues with error handling

### LINKED ISSUE #11: Error Handling
https://github.com/bitfocus/companion-module-magewell-ultrastream/blob/042d398941e02ebb82f01d25a916cb45154eabb1/src/client.ts#L51

@Julusian I saw an unhandled exception for an `ETIMEDOUT` that traced back to here.  The `get()` commands all should have `.catch((e) => {}}` implemented?

@omeaart, fyi

### PR DESCRIPTION
**Pull request by omeaart**
This pull requests fixes the missing error handling on the axios calls, also some dependencies were upgraded. Resolves #11

### CODE REVIEW

File: src/client.ts [hunk 1]
```diff
@@ -6,74 +6,92 @@ import { GetStatusResponse, BaseResponse, ApiResultCode, GetSettingsResponse } f
...
-      return;
+      this.instance.status(this.instance.STATUS_WARNING, 'Connecting');
+
+      const password = Md5.hashStr(this.instance.config.password);
+      return await axios.get(`http://${this.instance.config.host}/usapi?method=login&id=${this.instance.config.username}&pass=${password}`)
+        .catch(() => {
+          this.instance.log('warn', 'Authentication failed.');
+          this.instance.status(this.instance.STATUS_ERROR, 'Authentication failed');
+        }).then(async result => {
+          if (result == null) return;
```
Comment (Julusian) [inline src/client.ts:64]:
```suggestion
          if (!result) return;
```

File: src/client.ts [hunk 2]
```diff
@@ -6,74 +6,92 @@ import { GetStatusResponse, BaseResponse, ApiResultCode, GetSettingsResponse } f
...
-
-      if (result.data.result == ApiResultCode.errNeedAuth || result.data.result == ApiResultCode.errPasswd) {
-        // Auth error, try to reconnect
-        if (!retry) {
-          await this.initialize(true);
-          return await this.get<T>(method, params, true);
+    }).catch(e => {
+      this.instance.log('warn', method + ' call failed:' + e.response?.data.result);
+    }).then(async result => {
+      if (result == null) return;
```
Comment (Julusian) [inline src/client.ts:26]:
```suggestion
      if (!result) return;
```

**Review by Julusian — COMMENTED** [review]
I think result would end up as `undefined` rather than `null` following an error being caught by catch. So a looser falsey check is safer
